trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'rutzsco.demo-az-functions-python'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'Demo Account'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'MLR-API-CI'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'demo-funtion-python-api-ci'
    resourceGroupName: 'demo-funtion-python-api-ci'
    storageAccountName: 'azfpapici'
    region: 'East US'
    packageName: 'App.zip'
